import { Pokemon } from "../../tipos/Pokemon";
import { Comprimento } from "../../tipos/Comprimento";
import { TipoPokemon } from "../../tipos/TipoPokemon";
import * as Imagems from "./Imagens";

export const DicionarioEstiloLargura: Record<Comprimento, string> = {
  16: "w-16",
  24: "w-24",
  36: "w-36",
  48: "w-48",
  128: "w-128",
  144: "w-144",
};

export const DicionarioEstiloAltura: Record<Comprimento, string> = {
  16: "h-20",
  24: "h-24",
  36: "h-36",
  48: "h-48",
  128: "h-128",
  144: "h-144",
};

export const DicionarioTipoPokemonCor: Record<TipoPokemon, string> = {
  AGUA: "#2d91ff",
  FOGO: "#ff6132",
  PLANTA: "#40bf27",
  INSETO: "#9ca025",
  NORMAL: "#989898",
  VENENO: "#9850ce",
  VOADOR: "#96cafc",
};

export const listaPokemon: Array<Pokemon> = [
  {
    nDex: 1,
    nome: "Bulbassauro",
    tipoPrimario: TipoPokemon.PLANTA,
    tipoSecundario: TipoPokemon.VENENO,
    evoluirPara: ["Ivyssauro"],
    inicial: true,
    descricao:
      "Este Pokémon nasce com uma semente nas costas. A semente cresce lentamente com o tempo.",
    imagem: Imagems.Bulbassauro,
  },
  {
    nDex: 2,
    nome: "Ivyssauro",
    tipoPrimario: TipoPokemon.PLANTA,
    tipoSecundario: TipoPokemon.VENENO,
    evoluirPara: ["Venussauro"],
    inicial: false,
    descricao:
      "Quando o bulbo nas costas cresce, parece perder a capacidade de ficar em pé nas patas traseiras.",
    imagem: Imagems.Ivyssauro,
  },
  {
    nDex: 3,
    nome: "Venussauro",
    tipoPrimario: TipoPokemon.PLANTA,
    tipoSecundario: TipoPokemon.VENENO,
    inicial: false,
    descricao:
      "A planta floresce quando está absorvendo energia solar. Ele permanece em movimento para buscar a luz do sol.",
    imagem: Imagems.Venussauro,
  },
  {
    nDex: 4,
    nome: "Charmander",
    tipoPrimario: TipoPokemon.FOGO,
    inicial: true,
    descricao:
      "Obviamente prefere lugares quentes. Quando chove, diz-se que o vapor jorra da ponta de sua cauda.",
    evoluirPara: ["Charmeleon"],
    imagem: Imagems.Charmander,
  },
  {
    nDex: 5,
    nome: "Charmeleon",
    tipoPrimario: TipoPokemon.FOGO,
    inicial: false,
    descricao:
      "Tem uma natureza bárbara. Em batalha, ele chicoteia sua cauda de fogo e corta com garras afiadas.",
    evoluirPara: ["Charizard"],
    imagem: Imagems.Charmeleon,
  },
  {
    nDex: 6,
    nome: "Charizard",
    tipoPrimario: TipoPokemon.FOGO,
    tipoSecundario: TipoPokemon.VOADOR,
    inicial: false,
    descricao: "Ele parece um dragão só que não é um dragão",
    imagem: Imagems.Charizard,
  },
  {
    nDex: 7,
    nome: "Squirtle",
    tipoPrimario: TipoPokemon.AGUA,
    inicial: true,
    descricao: "",
    evoluirPara: ["Wartortle"],
    imagem: Imagems.Squirtle,
  },
  {
    nDex: 8,
    nome: "Wartortle",
    tipoPrimario: TipoPokemon.AGUA,
    inicial: false,
    descricao: "",
    evoluirPara: ["Blastoise"],
    imagem: Imagems.Wartortle,
  },
  {
    nDex: 9,
    nome: "Blastoise",
    tipoPrimario: TipoPokemon.AGUA,
    inicial: false,
    descricao: "",
    imagem: Imagems.Blastoise,
  },
  {
    nDex: 10,
    nome: "Caterpie",
    tipoPrimario: TipoPokemon.INSETO,
    inicial: false,
    descricao:
      "Caterpie é um Pokémon parecido com uma largata que é principalmente de cor verde com uma parte inferior bronzeada",
    imagem: Imagems.Caterpie,
    evoluirPara: ["Metapod"],
  },
  {
    nDex: 11,
    nome: "Metapod",
    tipoPrimario: TipoPokemon.INSETO,
    inicial: false,
    descricao: "",
    imagem: Imagems.Metapod,
    evoluirPara: ["Butterfree"],
  },
  {
    nDex: 12,
    nome: "Butterfree",
    tipoPrimario: TipoPokemon.INSETO,
    tipoSecundario: TipoPokemon.VOADOR,
    inicial: false,
    descricao: "",
    imagem: Imagems.Butterfree,
  },
  {
    nDex: 13,
    nome: "Weedle",
    tipoPrimario: TipoPokemon.INSETO,
    tipoSecundario: TipoPokemon.VENENO,
    inicial: false,
    descricao: "",
    imagem: Imagems.Weedle,
    evoluirPara: ["Kakuna"],
  },
  {
    nDex: 14,
    nome: "Kakuna",
    tipoPrimario: TipoPokemon.INSETO,
    tipoSecundario: TipoPokemon.VENENO,
    inicial: false,
    descricao: "",
    imagem: Imagems.Kakuna,
    evoluirPara: ["Beedrill"],
  },
  {
    nDex: 15,
    nome: "Beedrill",
    tipoPrimario: TipoPokemon.INSETO,
    tipoSecundario: TipoPokemon.VENENO,
    inicial: false,
    descricao: "",
    imagem: Imagems.Beedrill,
  },
  {
    nDex: 16,
    nome: "Pidgey",
    tipoPrimario: TipoPokemon.NORMAL,
    tipoSecundario: TipoPokemon.VOADOR,
    inicial: false,
    descricao:
      "Pidgey é um Pokémon ave pequeno e rechonchudo. É principalmente marrom com uma face, parte inferior e penas de voo de cor creme.",
    imagem: Imagems.Pidgey,
    evoluirPara: ["Pidgeotto"],
  },
  {
    nDex: 17,
    nome: "Pidgeotto",
    tipoPrimario: TipoPokemon.NORMAL,
    tipoSecundario: TipoPokemon.VOADOR,
    inicial: false,
    descricao: "",
    imagem: Imagems.Pidgeotto,
    evoluirPara: ["Pidgeot"],
  },
  {
    nDex: 18,
    nome: "Pidgeot",
    tipoPrimario: TipoPokemon.NORMAL,
    tipoSecundario: TipoPokemon.VOADOR,
    inicial: false,
    descricao: "",
    imagem: Imagems.Pidgeot,
  },
  {
    nDex: 19,
    nome: "Rattata",
    tipoPrimario: TipoPokemon.NORMAL,
    inicial: false,
    descricao: "",
    imagem: Imagems.Rattata,
    evoluirPara: ["Raticate"],
  },
  {
    nDex: 20,
    nome: "Raticate",
    tipoPrimario: TipoPokemon.NORMAL,
    inicial: false,
    descricao: "",
    imagem: Imagems.Raticate,
  },
];
